#!/bin/bash
#-----------------------------
#
# If first argument is set to dev, it will install development dependencies as well as production dependencies.
#
#-----------------------------

function error_message {
	echo -e "\e[93;101m$1\e[0m"
}

function success_message {
	echo -e "\e[30;102m$1\e[0m"
}

function test_composer
{
	composer > /dev/null 2> /dev/null
	if [ $? != "0" ]; then
		error_message " Composer not found. It must be accessible globally. "
		return 1
	fi
	return 0
}

function test_npm
{
	npm help > /dev/null 2> /dev/null
	if [ $? != "0" ]; then
		error_message " Node package manager (npm) not found. It must be accesible globally. "
		return 1
	fi
	return 0
}

function empty_dir {
	if [ -d $1 ]; then
		rm -rf $1 > /dev/null 2> /dev/null
		if [ $? == "0" ]; then
			success_message " Directory $1 removed. "
		else
			error_message " Directory $1 can't be removed. "
		fi
	else
		error_message " Path $1 is not a directory! "
	fi
}

function remove_file {
	if [ -f $1 ]; then
		rm -f $1 > /dev/null 2> /dev/null
		if [ $? == "0" ]; then
			success_message " File $1 removed. "
		else
			error_message " File $1 can't be removed. "
		fi
	else
		error_message " Path $! is not a file! "
	fi
}

function make_dir {
	if [ -d $1 ]; then
		error_message " Directory $1 already exists. "
	else
		mkdir $1 > /dev/null 2> /dev/null
		if [ $? == "0" ]; then
			success_message " Directory $1 created successfully. "
		else
			error_message " Directory $1 can't be created. "
		fi
	fi
}

function link_dir {
	if [ -d $1 ]; then
		ln -sd $1 $2 > /dev/null 2> /dev/null
		if [ $? == "0" ]; then
			success_message " Directory $1 linked to $2. "
		else
			error_message " Directory $1 can't be linked to $2. "
		fi
	else
		error_message " Source directory $1 can't be found. "
	fi
}

function link_file {
	if [ -f $1 ]; then
		ln -s $1 $2 > /dev/null 2> /dev/null
		if [ $? == "0" ]; then
			success_message " File $1 linked to $2. "
		else 
			error_message " File $1 can't be linked to $2. "
		fi
	else
		error_message " Source file $1 can't be found. "
	fi
}

if [ "$(id -u)" != "0" ]; then
    error_message " Run this script as root! "
    exit 1
fi

test_composer
if [ $? != "0" ]; then
	exit 1
fi

test_npm
if [ $? != "0" ]; then
	exit 1
fi

COMPOSER_PARAMS=""
NPM_PARAMS=""
BOWER_PARAMS="--allow-root"

if [ "$1" != "dev" ]; then
    COMPOSER_PARAMS="--no-dev"
    NPM_PARAMS="--production"
    BOWER_PARAMS="$BOWER_PARAMS --production"
fi

echo "Installation of dependencies with composer ..."

echo "Running: composer install $COMPOSER_PARAMS"

composer install $COMPOSER_PARAMS

echo "... done."

echo "Installation of dependencies with npm ..."

echo "Running: npm install $NPM_PARAMS"

npm install $NPM_PARAMS

echo "... done."

echo "Installation of dependencies with bower ..."

echo "Running: node_modules/bower/bin/bower install $BOWER_PARAMS"

node_modules/bower/bin/bower install $BOWER_PARAMS

echo "... done."

CD="$(pwd)"

mathjax="vendor/mathjax/mathjax"
pmathjax="public/js/mathjax"

echo "Copying references to mathjax ..."
empty_dir "$CD/$pmathjax"
make_dir "$CD/$pmathjax"
link_file "$CD/$mathjax/MathJax.js" "$CD/$pmathjax/MathJax.js"
link_dir "$CD/$mathjax/config" "$CD/$pmathjax/config"
link_dir "$CD/$mathjax/fonts" "$CD/$pmathjax/fonts"
link_dir "$CD/$mathjax/extensions" "$CD/$pmathjax/extensions"
link_dir "$CD/$mathjax/jax" "$CD/$pmathjax/jax"
link_dir "$CD/$mathjax/localization" "$CD/$pmathjax/localization"
chmod -R 755 "$CD/$pmathjax"
echo "... done."

highcharts="node_modules/highcharts"
phighcharts="public/js/highcharts"

echo "Copying references to highcharts ..."
empty_dir "$CD/$phighcharts"
make_dir "$CD/$phighcharts"
link_file "$CD/$highcharts/highcharts.js" "$CD/$phighcharts/highcharts.js"
link_file "$CD/$highcharts/highcharts-3d.js" "$CD/$phighcharts/highcharts-3d.js"
link_file "$CD/$highcharts/highcharts-more.js" "$CD/$phighcharts/highcharts-more.js"
link_file "$CD/$highcharts/highmaps.js" "$CD/$phighcharts/highmaps.js"
link_file "$CD/$highcharts/highstock.js" "$CD/$phighcharts/highstock.js"
link_dir "$CD/$highcharts/adapters" "$CD/$phighcharts/adapters"
link_dir "$CD/$highcharts/css" "$CD/$phighcharts/css"
link_dir "$CD/$highcharts/js" "$CD/$phighcharts/js"
link_dir "$CD/$highcharts/lib" "$CD/$phighcharts/lib"
link_dir "$CD/$highcharts/modules" "$CD/$phighcharts/modules"
link_dir "$CD/$highcharts/themes" "$CD/$phighcharts/themes"
chmod -R 755 "$CD/$phighcharts"
echo "... done."

fontAwesome="node_modules/font-awesome"
pFontAwesome="public/css/font-awesome"

echo "Copying references to font awesome ..."
empty_dir "$CD/$pFontAwesome"
make_dir "$CD/$pFontAwesome"
make_dir "$CD/$pFontAwesome/css"
link_file "$CD/$fontAwesome/css/font-awesome.min.css" "$CD/$pFontAwesome/css/font-awesome.min.css"
link_dir "$CD/$fontAwesome/fonts" "$CD/$pFontAwesome/fonts"
chmod -R 755 "$CD/$pFontAwesome"
echo "... done."

prettify="bower_components/google-code-prettify/src"
pprettify="public/js/google-code-prettify"
pprettifycss="public/css"

echo "Copying references to google-code-prettify ..."
empty_dir "$CD/$pprettify"
remove_file "$CD/$pprettifycss/prettify.css"
link_dir "$CD/$prettify" "$CD/$pprettify"
link_file "$CD/$prettify/prettify.css" "$CD/$pprettifycss/prettify.css"
chmod -R 755 "$CD/$pprettify"
chmod 755 "$CD/$pprettifycss/prettify.css"
echo "... done."

mmenu="node_modules/jquery.mmenu/dist"
pmmenu="public/js/jquery.mmenu"

echo "Copying references to jquery.mmenu ..."
empty_dir "$CD/$pmmenu"
link_dir "$CD/$mmenu" "$CD/$pmmenu"
chmod -R 755 "$CD/$pmmenu"
echo "... done."

tinymce="node_modules/tinymce"
ptinymce="public/js/tinymce4"

echo "Copying references to tinymce ..."
empty_dir "$CD/$ptinymce"
link_dir "$CD/$tinymce" "$CD/$ptinymce"
chmod -R 755 "$CD/$ptinymce"
echo "... done."
