#!/bin/bash

if [ "$(id -u)" != "0" ]; then
    echo "Run this script as root!"
    exit 1
fi

dpkg --get-selections | grep composer > /dev/null 2> /dev/null
if [ $? == "1" ]; then
    echo "Package composer can't be found!"
    exit 1
fi

composer install
