#!/bin/bash

#################################################
# Do not run this script manully.
#################################################

TESTFILE=$1
TIMEOUT=$2
BIN_PATH=$3
PYTHON_ARGS=""
#
nice $BIN_PATH/run_with_timeout $TIMEOUT /usr/bin/python3.4 $PYTHON_ARGS Test$TESTFILE.py
exit $? 
