#!/bin/bash
# using:
# parameter 1 = seconds to wait between executions
# parameter 2 = number of workers

if test "$#" -lt 2; then
	echo "Incorrect number of arguments, use run_workers <seconds to wait> <number of workers>"
	exit
fi

WAIT_TIME=$(( $1 / 2 ))

echo "Executing workers: $2 workers will be run approximately each $1 seconds."

while true; do
	for ((worker_id = 1; worker_id <= $2; worker_id++))
	do
		exec /opt/lampp/bin/php ../index.php cli_test index $worker_id &
		sleep 0.005
	done
	sleep $WAIT_TIME
	exec /opt/lampp/bin/php ../index.php cli_test aging &
	sleep $WAIT_TIME
done

