#!/bin/bash
# usage: testjava CLASS
# should be run from the directory private/test_to_execute/<unique random hash>
#
# test configuration variables:
#
OUTPUT_FILE=test.out
JAVAC_ARGS="-Xlint:unchecked -encoding UTF-8 -cp /usr/share/java/junit4.jar:. *.java"
#
rm -f *.class 2> /dev/null
#rm -rf */* 2> /dev/null
#rmdir * 2>/dev/null
#
mkdir out 2>/dev/null
chgrp testovac out
chmod g+rwx out
chgrp testovac .
chmod g+r .
#
echo "<pre>" > $OUTPUT_FILE
#
echo "<br />Compiling:<br />" >> $OUTPUT_FILE
/usr/bin/javac $JAVAC_ARGS 2>> $OUTPUT_FILE
javacexit=$?
if [[ $javacexit -ne 0 ]] ; then
  echo "<br />Compilation failed. You must correct the above errors before the tests will be run!<br />" >> $OUTPUT_FILE
else
#
  echo "<br />Running:<br />" >> $OUTPUT_FILE
  rm -f *.java 2> /dev/null
  cp -r * out 2> /dev/null
  rm -f out/$OUTPUT_FILE 2> /dev/null
  chgrp testovac out/* 2> /dev/null
  cd out
  echo "------------------------Testing with Test$1...<br />" >> $OUTPUT_FILE
  sudo -u testovac /opt/lampp/htdocs/list-svn/dev/test_scripts/testjava2 $1 >> ../$OUTPUT_FILE 2>> ../$OUTPUT_FILE
  cd .. ;
fi
#
rm -rf out 2>/dev/null
echo "------------------------Done.<br />" >> $OUTPUT_FILE
echo "</pre>" >> $OUTPUT_FILE
