#!/bin/bash
# usage: testpython MODULE
# should be run from the directory private/test_to_execute/<unique random hash>
#
# test configuration variables:
#
TIMEOUT=90000
PYTHON_ARGS=""
#
nice /opt/lampp/htdocs/list-svn/dev/test_scripts/run_with_timeout $TIMEOUT /usr/bin/python $PYTHON_ARGS Test$1.py 
cd .. ;
