#!/bin/bash
# usage: test FOLDER CLASS LANGUAGE
# should be run from the directory private/test_to_execute/<unique random hash>
# the files/ subdirectory should contain all Test* and data files
#
# test configuration variables:
#
cd $1

if [[ "$3" == "JAVA" ]] ; then
  /opt/lampp/htdocs/list-svn/dev/test_scripts/testjava $2 $4 ;
fi
if [[ "$3" == "PYTHON" ]] ; then
  /opt/lampp/htdocs/list-svn/dev/test_scripts/testpython $2 $4 ;
fi
if [[ "$3" == "PYTHONIO" ]] ; then
  /opt/lampp/htdocs/list-svn/dev/test_scripts/testpythonio $2 $4 $5 ;
fi
