#!/bin/bash
# usage: test FOLDER CLASS LANGUAGE
# should be run from the directory private/test_to_execute/<unique random hash>
# the files/ subdirectory should contain all Test* and data files
#
# test configuration variables:
#
cd $1

echo $1

OUTPUT=0;

if [[ "$3" == "JAVA" ]] ; then
  /var/www/list-svn/svn/dev/test_scripts/development/testjava $2 $4 ;
  OUTPUT=$?
fi
if [[ "$3" == "PYTHON" ]] ; then
  /var/www/list-svn/svn/dev/test_scripts/development/testpython $2 $4 ;
  OUTPUT=$?
fi
if [[ "$3" == "PYTHONIO" ]] ; then
  /var/www/list-svn/svn/dev/test_scripts/development/testpythonio $2 $4 $5 ;
  OUTPUT $?
fi
exit $OUTPUT
