#!/bin/bash
#
# test configuration variables:
TIMEOUT=90000
PYTHON_ARGS=""
#
cat ../test_data/test_input.txt | nice /var/www/list-svn/svn/dev/test_scripts/development/run_with_timeout $TIMEOUT /usr/bin/python $PYTHON_ARGS $1.py
cd .. ;
