#!/bin/bash
TEST_SOURCE_FILE=$1
STUDENT_SOURCE_FILE=$2
TIMEOUT=$3
WORKING_PATH=$4
BIN_PATH=`pwd`/test_scripts
RUN_FILE=strykoFedorLietajuciPes

COPTIONS=-Wno-write-strings

OUTPUT_FILE=$WORKING_PATH'__list_output.txt'
SCORING_FILE=$WORKING_PATH'__list_score.txt'

cd $WORKING_PATH
rm -f $RUN_FILE *.o
mv $TEST_SOURCE_FILE $TEST_SOURCE_FILE'.pending'
TRY_UCS2LE=0
echo "----- compiling... ----- <pre>" >> $OUTPUT_FILE
rm -f $OUTPUT_FILE'.x'
g++ $COPTIONS -c $(ls *.cpp *.CPP) >> $OUTPUT_FILE 2> $OUTPUT_FILE'.x'
RV1=$?
grep "error: stray" $OUTPUT_FILE'.x' > /dev/null
if [[ $? -eq 0 ]] ; then
  TRY_UCS2LE=1
fi

if [[ $TRY_UCS2LE -ne 0 ]] ; then
  rm -f $OUTPUT_FILE'.x'
  # echo "compiling failed, trying with UCS-2LE encoding..." >> $OUTPUT_FILE
  mv list_simple_cpp_test.cpp list_simple_cpp_test.cpp.pending
  for x in *.cpp *.CPP ; do mv $x conv.$x ; iconv -f UCS-2LE -t utf-8 conv.$x -o $x ; rm conv.$x ; done 
  g++ $COPTIONS -c $(ls *.cpp *.CPP) >> $OUTPUT_FILE 2> $OUTPUT_FILE'.x'
  RV1=$?
  mv list_simple_cpp_test.cpp.pending list_simple_cpp_test.cpp
  g++ $COPTIONS -c list_simple_cpp_test.cpp 
  head --lines=1 $OUTPUT_FILE'.x' >> $OUTPUT_FILE
fi

if [[ $RV1 -ne 0 ]] ; then
  echo "</pre><br>----- compilation did not work out well, please fix your errors, upload a new version and try again -----<br>" >> $OUTPUT_FILE
  echo "<pre>" >> $OUTPUT_FILE
  cat $OUTPUT_FILE'.x' >> $OUTPUT_FILE
  echo "</pre>" >> $OUTPUT_FILE
  rm -f $OUTPUT_FILE'.x'
else
  rm -f $OUTPUT_FILE'.x'
  strip --strip-symbol main *.o
  mv $TEST_SOURCE_FILE'.pending' $TEST_SOURCE_FILE
  if ! g++ $COPTIONS -c $TEST_SOURCE_FILE ; then
    echo "</pre><br>----- compiling of test failed, this is our fault! please send us a mail! -----<pre>" >> $OUTPUT_FILE
  else
    echo "</pre><br>----- linking with test... -----<br><pre>" >> $OUTPUT_FILE 
    g++ -o $RUN_FILE *.o >> $OUTPUT_FILE 2>> $OUTPUT_FILE
    if [[ $? -ne 0 ]] ; then
      echo "</pre><br>----- linking did not work out well, please fix your errors, upload a new version and try again ----<br><pre>" >> $OUTPUT_FILE
    else
      echo "</pre><br>----- running test, timeout time is $TIMEOUT ms... -----<br><pre>" >> $OUTPUT_FILE
      chgrp testovac . 
      chmod g+w .
      sudo -u testovac $BIN_PATH/run_cpp_simple_test $BIN_PATH $TIMEOUT $WORKING_PATH$RUN_FILE $SCORING_FILE  >> $OUTPUT_FILE 2>> $OUTPUT_FILE
      echo "</pre><br>----- run finished with `cat $SCORING_FILE` % success -----<br>" >> $OUTPUT_FILE
    fi
  fi
fi


