#!/bin/bash
# usage: testjava2 CLASS 
# should be run from the directory private/test_to_execute/<unique random hash>
#
# test configuration variables:
#
# TIMEOUT=90000
MY_DIR=$( cd "$( dirname "$0" )" && pwd )
TIMEOUT=$2
JAVA_ARGS="-Xmx128m -cp /usr/share/java/junit4.jar:."
#
nice $MY_DIR/run_with_timeout $TIMEOUT /usr/bin/java $JAVA_ARGS org.junit.runner.JUnitCore Test$1 | grep --text -v "at junit." |grep --text -v "at org.junit." |grep --text -v "at sun.reflect." |grep --text -v "at java.lang.reflect.Method.invoke" 
