#!/bin/bash
# usage: test FOLDER CLASS LANGUAGE
# should be run from the directory private/test_to_execute/<unique random hash>
# the files/ subdirectory should contain all Test* and data files
#
# test configuration variables:
#
MY_DIR=$( cd "$( dirname "$0" )" && pwd )
cd $1
retval=0

if [[ "$3" == "JAVA" ]] ; then
  $MY_DIR/testjava $2 $4 ;
  retval=$?
fi
if [[ "$3" == "PYTHON" ]] ; then
  $MY_DIR/testpython $2 $4 ;
  retval=$?
fi
exit $retval
