#!/bin/bash

ARGUMENTS="-sp $1 -tp $2 -t $3 -m $4 -cut $5 -bf $6 -mp $7"
nice /opt/lampp/htdocs/list-svn/dev/comparator/run_with_timeout $8 /usr/bin/java -jar /opt/lampp/htdocs/list-svn/dev/comparator/comparator.jar $ARGUMENTS

